### ISSUE TITLE
Basic C++ Syntax

### ISSUE THREAD

**Issue by arifyunando** [bellshade/CPP#29]
### General Information
Pemograman pada hakekatnya adalah proses perencanaan dan perancangan seperangkat perintah atau tugas tertentu yang akan dijalankan oleh komputer. Perintah atau tugas ini termasuk diantaranya operasi aritmatik, pengaturan alur kerja proses, pengulangan, dll. Pembahasan tata cara penulisan dalam bahasa C++ akan dibahas dalam issue ini

### Development
Berikut adalah topik - topik yang akan dicover untuk Basic C++ Syntax

- [x] Introduction
- [x] Variable and data type
- [x] pointer and reference
- [x] operator
- [x] conditional
- [x] looping
- [x] array
- [x] dynamic array (8_dynamic_array)
- [x] multidimensional array (9_multidimensional_array)
- [x] function (10_function)
- [x] recursion (11_recursion)
- [ ] class and struct (12_class_struct)

### Information for Contributors
Bagi teman-teman yang ingin melakukan kontribusi untuk topik-topik di atas, silahkan komen di dalam issue ini. Terima kasih.

#### Terms
- Baca dan ikuti arahan di [CONTRIBUTING.md](https://github.com/bellshade/CppAlgorithm/blob/main/CONTRIBUTING.md)
- Tidak menggunakan `using namespace std;`

#### Tasks
- Penjelasan dalam README.md
- File `.cpp` yang bisa dieksekusi
