### ISSUE TITLE
Menghilangkan using namespace std pada beberapa kode program

### ISSUE THREAD

**Issue by mushonnip** [bellshade/CPP#44]
### General Information
Beberapa kode program masih mempunyai `using namespace std;` dimana itu tidak diperbolehkan lagi menurut issue #29, sebenarnya saya juga masih kurang paham motivasi dari melarang hal tersebut.

### Task / Development
Di bawah ini beberapa kode program yang masih menggunakan `using namespace std;`

- [x] Fix [hello_world.cpp](https://github.com/bellshade/CPP/blob/main/basic/1_introduction/hello_world.cpp)
- [x] Fix [ternary.cpp](https://github.com/bellshade/CPP/blob/main/basic/5_conditional/ternary.cpp)
- [x] Fix [conditional.cpp](https://github.com/bellshade/CPP/blob/main/basic/5_conditional/conditional.cpp)

### Additional Information
Sebelumnya saya membuat pull request #40 mengenai ini, hanya saja setelah saya cek lagi masih ada beberapa kode program yang masih menggunakannya.
